name: Destroy the Kubernetes Cluster

on:
  schedule:
    - cron: 0 8 * * *

jobs:
  check_drift:
    runs-on: ubuntu-latest
    name: Destroy the Kubernetes Cluster
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform fmt
        id: fmt
        run: terraform destroy